name: Deploy

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.CONFIG }} # ssh_config; optional
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      
      - name: Check if project exist
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            if [ -d "shirt-designer" ]; then
              cd shirt-designer
            else
              git clone git@github.com:chadwithz/shirt-designer.git
              cd shirt-designer
            fi
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY}}

      - name: Build project
        run: |
          yarn install
          yarn build
      - name: Start server
        run: |
          pm2 list | grep "shirt-designer"
          if [ $? -eq 0 ]; then
            pm2 stop "shirt-designer"
            pm2 delete "shirt-designer"
          fi
          pm2 start npm --name "shirt-designer" -- start
